services:
    # cache:
    #   image: redis:7-alpine
    #   container_name: cache
    #   ports:
    #     - 6379:6379

    directus:
        image: directus/directus:11
        container_name: directus
        ports:
            - 9000:9000
        volumes:
            - ./config.json:/directus/config.json
            - ../_files/uploads:/directus/uploads
            - ./_data:/directus/database
            - ./extensions:/directus/extensions
        # depends_on:
        #   - cache
        environment:
            CONFIG_PATH: /directus/config.json
        secrets:
            - passwd
            - email
        extra_hosts:
            - "host.docker.internal:host-gateway"
        restart: unless-stopped

secrets:
    email:
        file: ../_secrets/email
    passwd:
        file: ../_secrets/passwd
