services:
    pgadmin:
        image: dpage/pgadmin4:9
        container_name: pgadmin
        ports:
            - "20000:80"
        volumes:
            - ./_data:/var/lib/pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: nirodhiko@outlook.com
            PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/passwd
        secrets:
            - passwd
        restart: unless-stopped

secrets:
    passwd:
        file: ../_secrets/passwd
